/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Mon Dec 18 21:38:43 1995
 */
extern int    altaz ( TOPOCENTRIC *infos, double pol[3], double J );
extern int    angles ( double p[], double q[], double e[] );
extern int    annuab ( double p[] );
extern double arcdot ( double p[], double q[] );
extern int    domoon ( TOPOCENTRIC *infos );
extern int    iter_trnsit ( int (*func)() );
extern int    moonll ( double J, double moonpp[], double moonpol[] );
extern int    gmoon ( double J, double rect[], double pol[] );
extern double mods3600 ( double x );
extern int    moon1 ( void );
extern int    moon2 ( void );
extern int    moon3 ( void );
extern int    moon4 ( int ltflag );
extern int    chewm ( short *p, int nlines, int nangles, int typflg, double ans[] );
extern int    showcname ( char *in );
extern int    relativity ( double p[], double q[], double e[] );
extern double deltat ( double Y );
extern int    update ( void );
extern int    diurab ( double last, double *ra, double *dec );
extern int    diurpx ( double last, double *ra, double *dec, double dist );
extern int    showrd ( char *msg, double p[], double pol[] );
extern int    showcor ( char *strng, double p[], double dp[] );
extern int    dms ( double x );
extern int    hms ( double x );
extern double zgetdate ( void );
extern double zgetdate_moi(int yearr, int monthh, int dayy) ;
extern double caltoj ( long year, int month, double day );
extern int    jtocal ( double J );
extern double mod360 ( double x );
extern double modtp ( double x );

extern double gethms ( void );
extern double gethms_moi(int hourr,int minn, int secc) ;

extern int    getnum ( char *msg, void *num, char *format );
extern int    getnum_moi( char s[40], void *num, char *format) ;

extern int    deltap ( double p0[], double p1[], double *dr, double *dd );
extern int    epsiln ( double J );
extern int    fk4fk5 ( double p[], double m[], struct star *el );
extern int    gplan ( double J, struct plantbl *plan, double pobj[] );
extern int    g3plan ( double J, struct plantbl *plan, double pobj[], int obj );
extern int    kepler ( double J, struct orbit *e, double rect[], double polar[] );
extern int    embofs ( double J, double emb[], double *r );
extern int    kinit ( void );
int           KINIT_ASTROKIT(double tlongg, double glatt, double heightt,double attempp, double atpresss, double jdflagg, double dtgivenn ) ;
extern int    getorbit ( struct orbit *el );
extern int    getstar ( struct star *el );
extern FILE *fincat ( char *name, int n, char *str1, char *str2 );
extern int    lightt ( struct orbit *elemnt, double q[], double e[] );
extern int    lonlat ( double pp[], double J, double polar[], int precess );
extern int    nutlo ( double J );
extern int    nutate ( double J, double p[] );
extern int    sscc ( int k, double arg, int n );
extern int    precess ( double R[], double J, int direction );
extern double refrac ( double alt );
extern int    reduce ( TOPOCENTRIC *infos, struct orbit *elemnt, double q[], double e[] );
extern int    doplanet (TOPOCENTRIC *infos);
extern int    rstar ( TOPOCENTRIC *infos, struct star *el );
extern int    dostar (TOPOCENTRIC *infos);
extern double sidrlt ( double j, double tlong );
extern int    dosun ( TOPOCENTRIC *infos );
extern double tdb ( double JED );
extern int    trnsit ( double J, double lha, double dec );
extern int    velearth ( double J );

extern double zatan2 ( double x, double y );
extern double acos(double);
extern double asin(double);
extern double atan(double);
extern double cos(double);
extern double sin(double);
extern double tan(double);
extern double sqrt(double);
extern double fabs(double);
extern double log(double);
extern double floor(double);
extern double sinh(double);
extern double cosh(double);
extern double tanh(double);

extern char  *whatconstel (double *, double);


