#!/bin/sh

/sbin/modprobe lirc_rpi gpio_in_pin=7
/sbin/modprobe lirc_dev
/sbin/loadkmap < /root/fr.kmap

if [ ! -f /etc/dbkey ]
then
    dropbearkey -t rsa -f /etc/dbkey
fi
dropbear -r /etc/dbkey
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

